### ISSUE TITLE
sbi_db_version should be cff_db_version.

### ISSUE THREAD

**Issue by ca-evan** [smashballoon/custom-facebook-feed#32]
Line 86 within the file `custom-facebook-feed.php`. It seems you've got this mixed up with another plugin of yours. It causes an issue over on the Instagram feed where cache is constantly busted.

**Comment by craigschlegel** [comment]
-- Please reply above this line --


Hey Smashballoon/custom-Facebook-Feed,

Thanks for contacting us. We've received your request and a member of
our team will get back to you as soon as possible.

In the meantime, we hope you're having a great day.

Team Smash Balloon

**Comment by johnnybrackett** [comment]
Thanks for letting us know @ca-evan - we'll get this fixed in the next update!

**Comment by johnnybrackett** [comment]
Fixed in v2.16

**Comment by craigschlegel** [comment]
-- Please reply above this line --


Hey Smashballoon/custom-Facebook-Feed,

Thanks for contacting us. We've received your request and a member of
our team will get back to you as soon as possible.

In the meantime, we hope you're having a great day.

Team Smash Balloon
